import AppKit

/// 履歴 1 件分。
///
/// 再コピー時に元の見た目を保つため、pasteboard に載っていた型を
/// そのまま辞書で持ち、書き戻すときに全型をまとめて戻す。
struct ClipboardItem: Identifiable, Sendable {
    enum Kind: Sendable {
        case text
        case fileURL

        var systemImage: String {
            switch self {
            case .text: return "text.alignleft"
            case .fileURL: return "doc"
            }
        }
    }

    let id = UUID()
    /// 型（UTType 文字列）→ 生データ。書き戻しにそのまま使う。
    let payload: [String: Data]
    /// 一覧に出す 1 行のプレビュー。
    let preview: String
    let kind: Kind
    let copiedAt: Date
    /// コピー元アプリの bundle ID。除外リストの判定と表示に使う。
    let sourceBundleID: String?
    /// サイズ上限を超えたため中身を保持していない。プレビューだけ出す。
    let isTruncated: Bool

    /// 同じ内容を続けてコピーしたときに重複させないための比較キー。
    var dedupeKey: String { "\(kind)\u{1}\(preview)" }
}

// MARK: - pasteboard との相互変換

extension ClipboardItem {
    /// 1 項目あたりのデータ上限。これを超えるものはプレビューだけ残す。
    static let maxPayloadBytes = 1024 * 1024

    /// 履歴に載せる型。この順に見て最初に取れたものを種別とする。
    /// RTF・画像は PR3 で足す。
    private static let textType = NSPasteboard.PasteboardType.string.rawValue
    private static let fileURLType = NSPasteboard.PasteboardType.fileURL.rawValue

    /// 履歴に載せてはいけない型。
    ///
    /// パスワードマネージャなどが付ける印で、nspasteboard.org の慣行として
    /// 広く使われている。型リストに含まれるかを見るだけなので安価。
    static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// pasteboard の現在の中身から履歴項目を作る。
    ///
    /// 履歴に載せない場合（機密フラグ付き、対応する型が無い、空）は nil。
    static func read(
        from pasteboard: NSPasteboard,
        sourceBundleID: String?,
        now: Date
    ) -> ClipboardItem? {
        let types = (pasteboard.types ?? []).map(\.rawValue)
        guard !types.isEmpty else { return nil }
        // 機密フラグは他の型より先に見る。読み出す前に捨てる。
        guard concealedTypes.isDisjoint(with: types) else { return nil }

        let kind: Kind
        let preview: String
        if let url = pasteboard.string(forType: .fileURL).flatMap(URL.init(string:)) {
            kind = .fileURL
            preview = url.path
        } else if let text = pasteboard.string(forType: .string) {
            // 空白だけのコピーは履歴を汚すだけなので載せない。
            guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
            kind = .text
            preview = Self.makePreview(from: text)
        } else {
            // 画像など未対応の型しか無い場合は静かに無視する。
            return nil
        }

        // 書き戻しに使う型だけを持つ。装飾的な型まで抱えるとメモリが膨らむ。
        let wanted = [textType, fileURLType]
        var payload: [String: Data] = [:]
        var total = 0
        for type in wanted where types.contains(type) {
            guard let data = pasteboard.data(forType: .init(type)) else { continue }
            total += data.count
            payload[type] = data
        }

        let truncated = total > maxPayloadBytes
        return ClipboardItem(
            payload: truncated ? [:] : payload,
            preview: preview,
            kind: kind,
            copiedAt: now,
            sourceBundleID: sourceBundleID,
            isTruncated: truncated
        )
    }

    /// 履歴から選ばれたときに pasteboard へ戻す。
    /// 中身を持っていない（上限超過）場合は何もせず false を返す。
    @discardableResult
    func writeBack(to pasteboard: NSPasteboard) -> Bool {
        guard !isTruncated, !payload.isEmpty else { return false }
        pasteboard.clearContents()
        for (type, data) in payload {
            pasteboard.setData(data, forType: .init(type))
        }
        return true
    }

    /// 改行を潰して 1 行に畳む。長すぎるものは切る。
    private static func makePreview(from text: String) -> String {
        let flattened = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .split(whereSeparator: \.isNewline)
            .joined(separator: " ")
        return flattened.count > 120 ? String(flattened.prefix(120)) + "…" : flattened
    }
}
