import AppKit

/// 履歴 1 件分。
///
/// 再コピー時に元の見た目を保つため、pasteboard に載っていた型を
/// そのまま辞書で持ち、書き戻すときに全型をまとめて戻す。
///
/// 画像だけは例外で、常駐アプリのメモリに数 MB を抱えないよう、
/// 実データをディスクへ退避し（`blobURL`）メモリにはサムネイルだけ残す。
struct ClipboardItem: Identifiable, Sendable, Codable {
    enum Kind: String, Sendable, Codable {
        case text
        case fileURL
        case rtf
        case image

        var systemImage: String {
            switch self {
            case .text: return "text.alignleft"
            case .fileURL: return "doc"
            case .rtf: return "doc.richtext"
            case .image: return "photo"
            }
        }
    }

    let id: UUID
    /// 型（UTType 文字列）→ 生データ。書き戻しにそのまま使う。
    /// 画像を退避したあとは空になり、代わりに `blobURL` を見る。
    var payload: [String: Data]
    /// 一覧に出す 1 行のプレビュー。画像は退避後に大きさを添える。
    var preview: String
    let kind: Kind
    let copiedAt: Date
    /// コピー元アプリの bundle ID。除外リストの判定に使う。
    let sourceBundleID: String?
    /// サイズ上限を超えたため中身を保持していない。プレビューだけ出す。
    let isTruncated: Bool
    /// 取り込んだときのデータ量。画像の重複判定に使う。
    var byteCount: Int = 0
    /// 退避した画像の実データの場所。`payload` の代わりに書き戻しへ使う。
    var blobURL: URL?
    /// 退避先に書いた形式。取り違えると貼り付け先が壊れた画像を受け取る。
    var blobType: String?
    /// 元画像の大きさ。一覧に「3840×2160」と添えるため。
    var pixelWidth: Int?
    var pixelHeight: Int?
    /// 一覧に出す縮小画像（PNG）。NSImage を持つと Sendable でなくなるのでバイト列で持つ。
    var thumbnailPNG: Data?

    init(
        id: UUID = UUID(),
        payload: [String: Data],
        preview: String,
        kind: Kind,
        copiedAt: Date,
        sourceBundleID: String?,
        isTruncated: Bool,
        byteCount: Int = 0,
        blobURL: URL? = nil,
        blobType: String? = nil,
        pixelWidth: Int? = nil,
        pixelHeight: Int? = nil,
        thumbnailPNG: Data? = nil
    ) {
        self.id = id
        self.payload = payload
        self.preview = preview
        self.kind = kind
        self.copiedAt = copiedAt
        self.sourceBundleID = sourceBundleID
        self.isTruncated = isTruncated
        self.byteCount = byteCount
        self.blobURL = blobURL
        self.blobType = blobType
        self.pixelWidth = pixelWidth
        self.pixelHeight = pixelHeight
        self.thumbnailPNG = thumbnailPNG
    }

    /// 同じ内容を続けてコピーしたときに重複させないための比較キー。
    ///
    /// 画像は表示名が「画像 1920×1080」のように大きさしか持たないため、
    /// これで比べると別々のスクリーンショットが同じ 1 件に潰れる。
    /// データ量を混ぜて、撮り直した別の画像を別物として扱う。
    var dedupeKey: String {
        kind == .image
            ? "image\u{1}\(byteCount)\u{1}\(pixelWidth ?? 0)x\(pixelHeight ?? 0)"
            : "\(kind.rawValue)\u{1}\(preview)"
    }

    /// 中身を持っていて書き戻せるか。
    var isRestorable: Bool {
        !isTruncated && (!payload.isEmpty || blobURL != nil)
    }
}

// MARK: - pasteboard との相互変換

extension ClipboardItem {
    /// テキスト系 1 項目あたりのメモリ上限。これを超えるものはプレビューだけ残す。
    /// 画像はディスクへ退避するのでこの制限を受けない。
    static let maxPayloadBytes = 1024 * 1024

    static let textType = NSPasteboard.PasteboardType.string.rawValue
    static let fileURLType = NSPasteboard.PasteboardType.fileURL.rawValue
    static let rtfType = NSPasteboard.PasteboardType.rtf.rawValue
    static let pngType = NSPasteboard.PasteboardType.png.rawValue
    static let tiffType = NSPasteboard.PasteboardType.tiff.rawValue

    /// 履歴に載せてはいけない型。
    ///
    /// パスワードマネージャなどが付ける印で、nspasteboard.org の慣行として
    /// 広く使われている。型リストに含まれるかを見るだけなので安価。
    static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// pasteboard の現在の中身から履歴項目を作る。
    ///
    /// 履歴に載せない場合（機密フラグ付き、対応する型が無い、空）は nil。
    /// 画像はここでは生データを抱えたまま返し、退避とサムネイル生成は
    /// 呼び出し側が `Task.detached` で行う（tick を長く止めないため）。
    static func read(
        from pasteboard: NSPasteboard,
        sourceBundleID: String?,
        now: Date
    ) -> ClipboardItem? {
        let types = (pasteboard.types ?? []).map(\.rawValue)
        guard !types.isEmpty else { return nil }
        // 機密フラグは他の型より先に見る。読み出す前に捨てる。
        guard concealedTypes.isDisjoint(with: types) else { return nil }

        let kind: Kind
        let preview: String
        // 種別は「具体的なものから先に」見る。画像には TIFF と一緒に
        // ファイル名のテキストが載ることがあり、テキストを先に見ると取り違える。
        if let url = pasteboard.string(forType: .fileURL).flatMap(URL.init(string:)) {
            kind = .fileURL
            preview = url.path
        } else if types.contains(pngType) || types.contains(tiffType) {
            kind = .image
            preview = "画像"
        } else if let text = pasteboard.string(forType: .string) {
            // 空白だけのコピーは履歴を汚すだけなので載せない。
            guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
            // 書式付きテキストは RTF も一緒に持ち帰り、貼り直しても書式を失わないようにする。
            kind = types.contains(rtfType) ? .rtf : .text
            preview = makePreview(from: text)
        } else {
            return nil
        }

        // 書き戻しに使う型だけを持つ。装飾的な型まで抱えるとメモリが膨らむ。
        let wanted: [String]
        switch kind {
        case .text: wanted = [textType]
        case .rtf: wanted = [rtfType, textType]
        case .fileURL: wanted = [fileURLType, textType]
        case .image: wanted = [pngType, tiffType]
        }

        var payload: [String: Data] = [:]
        var total = 0
        for type in wanted where types.contains(type) {
            guard let data = pasteboard.data(forType: .init(type)) else { continue }
            total += data.count
            payload[type] = data
        }
        guard !payload.isEmpty else { return nil }

        // 画像はディスクへ逃がすので上限を当てない。
        let truncated = kind != .image && total > maxPayloadBytes
        return ClipboardItem(
            payload: truncated ? [:] : payload,
            preview: preview,
            kind: kind,
            copiedAt: now,
            sourceBundleID: sourceBundleID,
            isTruncated: truncated,
            byteCount: total
        )
    }

    /// 履歴から選ばれたときに pasteboard へ戻す。
    /// 中身を持っていない（上限超過・退避先が消えた）場合は false。
    @discardableResult
    func writeBack(to pasteboard: NSPasteboard) -> Bool {
        guard !isTruncated else { return false }

        // 画像は退避先から読み直す。読めなければ何も壊さず諦める。
        if let blobURL, payload.isEmpty {
            guard let data = try? Data(contentsOf: blobURL) else { return false }
            pasteboard.clearContents()
            // 退避時に実際に書いた形式で戻す。PNG と偽ると貼り付け先が壊れる。
            pasteboard.setData(data, forType: .init(blobType ?? Self.pngType))
            return true
        }

        guard !payload.isEmpty else { return false }
        pasteboard.clearContents()
        for (type, data) in payload {
            pasteboard.setData(data, forType: .init(type))
        }
        return true
    }

    /// 改行を潰して 1 行に畳む。長すぎるものは切る。
    private static func makePreview(from text: String) -> String {
        let flattened = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .split(whereSeparator: \.isNewline)
            .joined(separator: " ")
        return flattened.count > 120 ? String(flattened.prefix(120)) + "…" : flattened
    }
}
